version: 2
builds:
  - main: ./cmd/rp-archiver/main.go
    binary: rp-archiver
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

changelog:
  filters:
    exclude:
      - "^Update CHANGELOG.md"

archives:
  - files:
      - LICENSE
      - README.md
